#!/usr/bin/env bash
# script that will display information about subdomains. 
# shellcheck disable=SC2086

if [ $# -eq 2 ]; then
    dig "$2.$1" | grep -A1 'ANSWER SECTION:'| grep -v 'ANSWER' | awk -v subd="$2" '{print "The subdomain "subd" is a "$4" record and points to "$5}'
else
    for var  in 'www' 'lb-01' 'web-01' 'web-02'; do
        dig "$var.$1" | grep -A1 'ANSWER SECTION:'| grep -v 'ANSWER' | awk -v subd="$var" '{print "The subdomain "subd" is a "$4" record and points to "$5}'
    done
fi
